-
  type: a
  attribute:
    data-id: rs:id
    onclick: PluginPluginAnalysis.plugin_clear_cache(this.getAttribute('data-id'))
    style:
      float: right
  innerHTML: Clear cache
-
  type: h1
  innerHTML: 
    -
      type: widget
      data:
        plugin: image/element
        method: render
        data:
          path: rs:icon_path
          style: 'height:30px'
    -
      type: span
      innerHTML: rs:name
-
  type: ul
  attribute:
    class: 'nav nav-tabs'
    id: my_navtabs
    role: tablist
  innerHTML:
    -
      type: li
      attribute:
        class: nav-item
        role: presentation
      innerHTML:
        -
          type: a
          attribute:
            class: nav-link
          innerHTML: General
    -
      type: li
      attribute:
        class: nav-item
        role: presentation
      innerHTML:
        -
          type: a
          attribute:
            class: nav-link
          innerHTML:
            -
              type: span
              innerHTML: Plugin
            -
              type: span
              settings:
                enabled: rs:conflict
              innerHTML: '(conflict)'
    -
      type: li
      attribute:
        class: nav-item
        role: presentation
      innerHTML:
        -
          type: a
          attribute:
            class: nav-link
          innerHTML: Readme
    -
      type: li
      attribute:
        class: nav-item
        role: presentation
      innerHTML:
        -
          type: a
          attribute:
            class: nav-link
          innerHTML: Theme usage
    -
      type: li
      attribute:
        class: nav-item
        role: presentation
      innerHTML:
        -
          type: a
          attribute:
            class: nav-link
          innerHTML: Plugin usage
    -
      type: li
      attribute:
        class: nav-item
        role: presentation
      innerHTML:
        -
          type: a
          attribute:
            class: nav-link
          innerHTML: History
    -
      type: li
      attribute:
        class: nav-item
        role: presentation
      innerHTML:
        -
          type: a
          attribute:
            class: nav-link
          innerHTML: Links
    -
      type: li
      attribute:
        class: nav-item
        role: presentation
      innerHTML:
        -
          type: a
          attribute:
            class: nav-link
          innerHTML: Public
    -
      type: li
      attribute:
        class: nav-item
        role: presentation
      innerHTML:
        -
          type: a
          attribute:
            class: nav-link
          innerHTML: I18N
-
  type: div
  attribute:
    style: 'margin-top:20px;min-height:300px'
    id: my_content
  innerHTML:
    -
      type: div
      attribute:
        id: tab_general
        class: plugin_bootstrap_navtabs_content
        style: 'display:none'
      innerHTML:
        -
          type: div
          innerHTML:
            -
              type: strong
              innerHTML: Version
            -
              type: span
              innerHTML: rs:version_manifest
        -
          type: div
          innerHTML:
            -
              type: strong
              innerHTML: Git
            -
              type: a
              settings:
                enabled: git:status
              attribute:
                data-id: rs:url_id
                data-version_manifest: rs:version_manifest
                onclick: PluginPluginAnalysis.git(this, '')
              innerHTML: git:has
        -
          type: div
          innerHTML:
            -
              type: strong
              innerHTML: Author
            -
              type: span
              innerHTML: manifest:author
        -
          type: div
          innerHTML:
            -
              type: strong
              innerHTML: Description
            -
              type: span
              innerHTML: manifest:description
        -
          type: div
          innerHTML:
            -
              type: strong
              innerHTML: Manifest
            -
              type: span
              innerHTML: rs:has_manifest
            -
              type: a
              settings:
                disabled: rs:manifest
              attribute:
                data-url_id: rs:url_id
                onclick: PluginPluginAnalysis.manifest_create(this)
              innerHTML: Create
        -
          type: div
          innerHTML:
            -
              type: strong
              innerHTML: Readme
            -
              type: span
              innerHTML: rs:has_readme
            -
              type: a
              settings:
                disabled: rs:readme
              attribute:
                data-url_id: rs:url_id
                onclick: PluginPluginAnalysis.readme_create(this)
              innerHTML: Create
        -
          type: div
          innerHTML:
            -
              type: strong
              attribute:
                class: content-colon
              innerHTML: License
            - 
              type: span
              innerHTML: rs:has_license_text
            -
              type: a
              settings:
                disabled: rs:has_license
              attribute:
                data-url_id: rs:url_id
                onclick: PluginPluginAnalysis.license_create(this)
              innerHTML: Create
        -
          type: div
          innerHTML:
            -
              type: strong
              innerHTML: Files
            -
              type: span
              innerHTML: rs:files_count
        -
          type: div
          settings:
            disabled: rs:has_public_folder
          innerHTML:
            -
              type: strong
              innerHTML: Public folder
            -
              type: span
              innerHTML: No
        -
          type: div
          settings:
            enabled: rs:has_public_folder
          attribute:
            class: well
          innerHTML:
            -
              type: div
              attribute:
                class: font-italic
              innerHTML: Public folder
            -
              type: div
              innerHTML:
                -
                  type: strong
                  innerHTML: Exist
                -
                  type: span
                  innerHTML: rs:has_public_folder_text
            -
              type: div
              settings:
                enabled: rs:has_public_folder
              innerHTML:
                -
                  type: strong
                  innerHTML: Has twin
                -
                  type: span
                  innerHTML: rs:has_public_folder_twin_text
                -
                  type: a
                  settings:
                    disabled: rs:has_public_folder_twin
                  attribute:
                    data-url_id: rs:url_id
                    onclick: PluginPluginAnalysis.public_create(this)
                    class: btn btn-success
                  innerHTML: Create
            -
              type: div
              settings:
                enabled: rs:has_public_folder
              innerHTML:
                -
                  type: strong
                  innerHTML: Match
                -
                  type: span
                  innerHTML: rs:public_folder_match_text
            -
              type: div
              settings:
                enabled: rs:has_public_folder_twin
              innerHTML:
                -
                  type: a
                  settings:
                    disabled: rs:public_folder_match
                  attribute:
                    data-url_id: rs:url_id
                    onclick: PluginPluginAnalysis.public_update(this)
                    class: btn btn-warning
                  innerHTML: Update
        -
          type: div
          innerHTML:
            -
              type: strong
              innerHTML:
                -
                  type: span
                  innerHTML: rs:js_name
            -
              type: span
              innerHTML: rs:has_js_text
            -
              type: a
              settings:
                disabled: rs:has_js
              attribute:
                data-url_id: rs:url_id
                onclick: PluginPluginAnalysis.js_create(this)
              innerHTML: Create
            -
              type: a
              settings:
                enabled: rs:has_js
              attribute:
                data-url_id: rs:url_id
                onclick: PluginPluginAnalysis.js_include_method(this)
              innerHTML: Include method
        -
          type: div
          attribute:
            class: row
          innerHTML:
            -
              type: div
              attribute:
                class: col-md-12
              innerHTML: webmaster:element
    -
      type: div
      attribute:
        id: tab_plugin
        class: plugin_bootstrap_navtabs_content
        style: 'display:none'
      innerHTML:
        -
          type: div
          settings:
            enabled: rs:plugins
          innerHTML:
            -
              type: div
              settings:
                enabled: true
              attribute:
                class: alert alert-warning
              innerHTML:
                -
                  type: a
                  attribute:
                    data-id: rs:id
                    onclick: PluginPluginAnalysis.versions_update(this)
                  innerHTML: Update versions
            -
              type: widget
              data:
                plugin: wf/table
                method: render_many
                data:
                  rs: rs:plugin
                  datatable:
                    disabled: false
                  field:
                    name_click: Plugin
                    icon_path: Icon
                    version_manifest: Version
                    version: Using
                    version_diff: Diff
                    conflict: Conflict
                    find: Find
                  element:
                    icon_path:
                      -
                        type: widget
                        data:
                          plugin: image/element
                          method: render
                          data:
                            path: wf_table:icon_path
                            style: 'width:30px'
            -
              type: div
              settings:
                disabled: rs:plugins
              attribute:
                style: 'font-style:italic'
              innerHTML: Has no plugin
    -
      type: div
      attribute:
        id: tab_readme
        class: plugin_bootstrap_navtabs_content
        style: 'display:none'
        data-url: rs:readme_url
      innerHTML:
    -
      type: div
      attribute:
        id: tab_theme_usage
        class: plugin_bootstrap_navtabs_content
        style: 'display:none'
        data-url: rs:theme_usage_url
      innerHTML:
    -
      type: div
      attribute:
        id: tab_plugin_usage
        class: plugin_bootstrap_navtabs_content
        style: 'display:none'
      innerHTML:
        -
          type: widget
          settings:
            enabled: rs:has_usage
          data:
            plugin: wf/table
            method: render_many
            data:
              rs: rs:usage
              datatable:
                disabled: false
              field:
                icon_path: Icon
                name: Name
              element:
                icon_path:
                  -
                    type: widget
                    data:
                      plugin: image/element
                      method: render
                      data:
                        path: wf_table:icon_path
                        style: 'width:30px'
    -
      type: div
      attribute:
        id: tab_history
        class: plugin_bootstrap_navtabs_content
        style: 'display:none'
      innerHTML:
        -
          type: p
          innerHTML:
            -
              type: a
              attribute:
                class: btn btn-primary
                data-id: request:id
                onclick: PluginPluginAnalysis.history_form(this.getAttribute('data-id'))
              innerHTML: Add
        -
          type: widget
          data:
            plugin: wf/table
            method: render_many
            data:
              field:
                date: Date
                version: Version
                title: Title
                description: Description
                webmaster: Webmaster
              rs: rs:history
              datatable:
                disabled: false
    -
      type: div
      attribute:
        id: tab_links
        class: plugin_bootstrap_navtabs_content
        style: 'display:none'
      innerHTML:
        -
          type: widget
          settings:
            enabled: rs:has_links
          data:
            plugin: wf/table
            method: render_many
            data:
              rs: rs:links
              datatable:
                disabled: false
    -
      type: div
      attribute:
        id: tab_public
        class: plugin_bootstrap_navtabs_content
        style: 'display:none'
      innerHTML:
        -
          type: widget
          data:
            plugin: wf/table
            method: render_many
            data:
              id: dt_public_folder_files
              field:
                name: Name
                exist: Exist
                size: LSize
                size_right: RSize
                size_diff: Diff
                left_time_text: LTime
                right_time_text: RTime
                left_is_newer: LNewer
              datatable:
                disabled: false
                ajax: rs:public_folder_files_url
        -
          type: script
          innerHTML: |
            $('#dt_public_folder_files tbody').on( 'click', 'tr', function () {
                PluginPluginAnalysis.dt_public_folder_files_row_click( datatable_dt_public_folder_files.row( this ).data() );
            } );
    -
      type: div
      attribute:
        id: tab_i18n
        class: plugin_bootstrap_navtabs_content
        style: 'display:none'
        data-url: rs:i18n_url
      innerHTML:
-
  type: script
  innerHTML: "PluginBootstrapNavtabs_v1.nav_init({ul: 'my_navtabs', content: 'my_content', click: 0});"
      