-
  type: h1
  innerHTML: rs:name
-
  type: div
  attribute:
    class: row
  innerHTML:
    -
      type: div
      attribute:
        class: col-md-4
      innerHTML:
        -
          type: div
          innerHTML:
            -
              type: widget
              data:
                plugin: image/element
                method: render
                data:
                  path: rs:icon_path
                  style: 'width:40px'
        -
          type: div
          innerHTML:
            -
              type: strong
              innerHTML: Version
            -
              type: span
              innerHTML: rs:version_manifest
        -
          type: div
          innerHTML:
            -
              type: strong
              innerHTML: Author
            -
              type: span
              innerHTML: manifest:author
        -
          type: div
          innerHTML:
            -
              type: strong
              innerHTML: Description
            -
              type: span
              innerHTML: manifest:description
        -
          type: div
          innerHTML:
            -
              type: strong
              innerHTML: Manifest
            -
              type: span
              innerHTML: rs:has_manifest
            -
              type: a
              settings:
                disabled: rs:manifest
              attribute:
                data-url_id: rs:url_id
                onclick: PluginPluginAnalysis.manifest_create(this)
              innerHTML: Create
        -
          type: div
          innerHTML:
            -
              type: strong
              innerHTML: Readme
            -
              type: span
              innerHTML: rs:has_readme
            -
              type: a
              settings:
                disabled: rs:readme
              attribute:
                data-url_id: rs:url_id
                onclick: PluginPluginAnalysis.readme_create(this)
              innerHTML: Create
        -
          type: div
          innerHTML:
            -
              type: strong
              innerHTML: Files
            -
              type: span
              innerHTML: rs:files_count
        -
          type: div
          settings:
            disabled: rs:has_public_folder
          innerHTML:
            -
              type: strong
              innerHTML: Public folder
            -
              type: span
              innerHTML: No
        -
          type: div
          settings:
            enabled: rs:has_public_folder
          attribute:
            class: well
          innerHTML:
            -
              type: h2
              innerHTML: Public folder
            -
              type: div
              innerHTML:
                -
                  type: strong
                  innerHTML: Exist
                -
                  type: span
                  innerHTML: rs:has_public_folder_text
            -
              type: div
              settings:
                enabled: rs:has_public_folder
              innerHTML:
                -
                  type: strong
                  innerHTML: Has twin
                -
                  type: span
                  innerHTML: rs:has_public_folder_twin_text
                -
                  type: a
                  settings:
                    disabled: rs:has_public_folder_twin
                  attribute:
                    data-url_id: rs:url_id
                    onclick: PluginPluginAnalysis.public_create(this)
                    class: btn btn-success
                  innerHTML: Create
            -
              type: div
              settings:
                enabled: rs:has_public_folder
              innerHTML:
                -
                  type: strong
                  innerHTML: Match
                -
                  type: span
                  innerHTML: rs:public_folder_match_text
            -
              type: div
              settings:
                enabled: rs:has_public_folder_twin
              innerHTML:
                -
                  type: a
                  settings:
                    disabled: rs:public_folder_match
                  attribute:
                    data-url_id: rs:url_id
                    onclick: PluginPluginAnalysis.public_update(this)
                    class: btn btn-warning
                  innerHTML: Update
        -
          type: div
          innerHTML:
            -
              type: strong
              innerHTML:
                -
                  type: span
                  innerHTML: rs:js_name
            -
              type: span
              innerHTML: rs:has_js_text
            -
              type: a
              settings:
                disabled: rs:has_js
              attribute:
                data-url_id: rs:url_id
                onclick: PluginPluginAnalysis.js_create(this)
              innerHTML: Create
            -
              type: a
              settings:
                enabled: rs:has_js
              attribute:
                data-url_id: rs:url_id
                onclick: PluginPluginAnalysis.js_include_method(this)
              innerHTML: Include method
    -
      type: div
      attribute:
        class: col-md-8
      innerHTML:
        -
          type: div
          attribute:
            class: well
          innerHTML:
            -
              type: h2
              innerHTML: Plugin
            -
              type: div
              settings:
                enabled: rs:plugins
              innerHTML:
                -
                  type: div
                  settings:
                    enabled: rs:conflict
                  attribute:
                    class: alert alert-warning
                  innerHTML: Has conflict
                -
                  type: widget
                  data:
                    plugin: wf/table
                    method: render_many
                    data:
                      rs: rs:plugin
                      field:
                        icon_path: Icon
                        name: Name
                        version: MV
                        version_manifest: PV
                        find: Find
                      element:
                        icon_path:
                          -
                            type: widget
                            data:
                              plugin: image/element
                              method: render
                              data:
                                path: wf_table:icon_path
                                style: 'width:30px'
            -
              type: div
              settings:
                disabled: rs:plugins
              attribute:
                style: 'font-style:italic'
              innerHTML: Has no plugin
        
-
  type: div
  attribute:
    class: row
  innerHTML:
    -
      type: div
      attribute:
        class: col-md-12
      innerHTML:
        -
          type: div
          attribute:
            class: well
          innerHTML:
            -
              type: div
              innerHTML: rs:readme
-
  type: div
  attribute:
    class: row
  innerHTML:
    -
      type: div
      attribute:
        class: col-md-12
      innerHTML:
        -
          type: div
          attribute:
            class: well
          innerHTML:
            -
              type: h2
              innerHTML: GIT
            -
              type: div
              innerHTML:
                -
                  type: strong
                  innerHTML: Has
                -
                  type: span
                  innerHTML: git:has
            -
              type: pre
              settings:
                enabled: git:status
              innerHTML: git:status
            -
              type: a
              settings:
                enabled: git:status
              attribute:
                data-id: rs:url_id
                onclick: PluginPluginAnalysis.git(this)
              innerHTML: More
-
  type: div
  attribute:
    class: row
  innerHTML:
    -
      type: div
      attribute:
        class: col-md-6
      innerHTML:
        -
          type: div
          attribute:
            class: well
          innerHTML:
            -
              type: h2
              innerHTML: Theme usage
            -
              type: widget
              settings:
                enabled: rs:theme_has_usage
              data:
                plugin: wf/table
                method: render_many
                data:
                  field:
                    name: Name
                    plugin: Widget
                    plugin_module: Page
                    event: Event
                  rs: rs:theme_usage
    -
      type: div
      attribute:
        class: col-md-6
      innerHTML:
        -
          type: div
          attribute:
            class: well
          innerHTML:
            -
              type: h2
              innerHTML: Plugin usage
            -
              type: widget
              settings:
                enabled: rs:has_usage
              data:
                plugin: wf/table
                method: render_many
                data:
                  rs: rs:usage
                  field:
                    icon_path: Icon
                    name: Name
                  element:
                    icon_path:
                      -
                        type: widget
                        data:
                          plugin: image/element
                          method: render
                          data:
                            path: wf_table:icon_path
                            style: 'width:30px'
-
  type: div
  attribute:
    class: row
  innerHTML:
    -
      type: div
      attribute:
        class: col-md-6
      innerHTML:
        -
          type: div
          attribute:
            class: well
          innerHTML:
            -
              type: h2
              innerHTML: History
            -
              type: widget
              data:
                plugin: wf/table
                method: render_many
                data:
                  field:
                    version: Version
                    date: Date
                    description: Description
                  rs: rs:history
    -
      type: div
      attribute:
        class: col-md-6
      innerHTML:
        -
          type: div
          attribute:
            class: well
          innerHTML:
            -
              type: h2
              innerHTML: Links
            -
              type: widget
              settings:
                enabled: rs:has_links
              data:
                plugin: wf/table
                method: render_many
                data:
                  rs: rs:links
-
  type: div
  attribute:
    class: row
  innerHTML:
    -
      type: div
      attribute:
        class: col-md-12
      innerHTML: webmaster:element
      