-
  type: h1
  innerHTML: rs:name
-
  type: div
  innerHTML:
    -
      type: strong
      innerHTML: Version
    -
      type: span
      innerHTML: rs:version_manifest
-
  type: div
  innerHTML:
    -
      type: strong
      innerHTML: Manifest
    -
      type: span
      innerHTML: rs:has_manifest
    -
      type: a
      settings:
        disabled: rs:manifest
      attribute:
        data-url_id: rs:url_id
        onclick: PluginPluginAnalysis.manifest_create(this)
      innerHTML: Create
-
  type: div
  innerHTML:
    -
      type: strong
      innerHTML: Files
    -
      type: span
      innerHTML: rs:files_count
-
  type: div
  attribute:
    class: well
  innerHTML:
    -
      type: div
      innerHTML:
        -
          type: strong
          innerHTML: Public folder
        -
          type: span
          innerHTML: rs:has_public_folder_text
    -
      type: div
      innerHTML:
        -
          type: strong
          innerHTML: Public folder twin
        -
          type: span
          innerHTML: rs:has_public_folder_twin_text
    -
      type: div
      innerHTML:
        -
          type: strong
          innerHTML: Public folder match
        -
          type: span
          innerHTML: rs:public_folder_match_text
-
  type: div
  settings:
    enabled: rs:plugins
  attribute:
    class: well
  innerHTML:
    -
      type: h2
      innerHTML: Plugin
    -
      type: div
      innerHTML:
        -
          type: strong
          innerHTML: Plugin conflict
        -
          type: span
          innerHTML: rs:conflict
    -
      type: widget
      data:
        plugin: wf/table
        method: render_many
        data:
          rs: rs:plugin
-
  type: div
  settings:
    disabled: rs:plugins
  attribute:
    class: well
    style: 'font-style:italic'
  innerHTML: Has no plugin
      