-
  type: h1
  innerHTML: rs:name
-
  type: div
  attribute:
    class: row
  innerHTML:
    -
      type: div
      attribute:
        class: col-md-6
      innerHTML:
        -
          type: div
          innerHTML:
            -
              type: strong
              innerHTML: Version
            -
              type: span
              innerHTML: rs:version_manifest
        -
          type: div
          innerHTML:
            -
              type: strong
              innerHTML: Author
            -
              type: span
              innerHTML: manifest:author
        -
          type: div
          innerHTML:
            -
              type: strong
              innerHTML: Description
            -
              type: span
              innerHTML: manifest:description
        -
          type: div
          innerHTML:
            -
              type: strong
              innerHTML: Manifest
            -
              type: span
              innerHTML: rs:has_manifest
            -
              type: a
              settings:
                disabled: rs:manifest
              attribute:
                data-url_id: rs:url_id
                onclick: PluginPluginAnalysis.manifest_create(this)
              innerHTML: Create
        -
          type: div
          innerHTML:
            -
              type: strong
              innerHTML: Readme
            -
              type: span
              innerHTML: rs:has_readme
            -
              type: a
              settings:
                disabled: rs:readme
              attribute:
                data-url_id: rs:url_id
                onclick: PluginPluginAnalysis.readme_create(this)
              innerHTML: Create
        -
          type: div
          innerHTML:
            -
              type: strong
              innerHTML: Files
            -
              type: span
              innerHTML: rs:files_count
        -
          type: div
          innerHTML:
            -
              type: strong
              innerHTML: Public folder exist
            -
              type: span
              innerHTML: rs:has_public_folder_text
        -
          type: div
          innerHTML:
            -
              type: strong
              innerHTML: Public folder twin
            -
              type: span
              innerHTML: rs:has_public_folder_twin_text
        -
          type: div
          innerHTML:
            -
              type: strong
              innerHTML: Public folder match
            -
              type: span
              innerHTML: rs:public_folder_match_text
-
  type: div
  attribute:
    class: row
  innerHTML:
    -
      type: div
      attribute:
        class: col-md-12
      innerHTML:
        -
          type: div
          attribute:
            class: well
          innerHTML:
            -
              type: h2
              innerHTML: Readme
            -
              type: div
              innerHTML: rs:readme
-
  type: div
  attribute:
    class: row
  innerHTML:
    -
      type: div
      attribute:
        class: col-md-6
      innerHTML:
        -
          type: div
          attribute:
            class: well
          innerHTML:
            -
              type: h2
              innerHTML: Plugin
            -
              type: div
              settings:
                enabled: rs:plugins
              innerHTML:
                -
                  type: div
                  settings:
                    enabled: rs:conflict
                  attribute:
                    class: alert alert-warning
                  innerHTML: Has conflict
                -
                  type: widget
                  data:
                    plugin: wf/table
                    method: render_many
                    data:
                      rs: rs:plugin
            -
              type: div
              settings:
                disabled: rs:plugins
              attribute:
                style: 'font-style:italic'
              innerHTML: Has no plugin
    -
      type: div
      attribute:
        class: col-md-6
      innerHTML:
        -
          type: div
          attribute:
            class: well
          innerHTML:
            -
              type: h2
              innerHTML: Plugin usage
            -
              type: widget
              settings:
                enabled: rs:has_usage
              data:
                plugin: wf/table
                method: render_many
                data:
                  rs: rs:usage
        -
          type: div
          attribute:
            class: well
          innerHTML:
            -
              type: h2
              innerHTML: Theme usage
            -
              type: widget
              settings:
                enabled: rs:theme_has_usage
              data:
                plugin: wf/table
                method: render_many
                data:
                  rs: rs:theme_usage
-
  type: div
  attribute:
    class: row
  innerHTML:
    -
      type: div
      attribute:
        class: col-md-6
      innerHTML:
        -
          type: div
          attribute:
            class: well
          innerHTML:
            -
              type: h2
              innerHTML: History
            -
              type: widget
              data:
                plugin: wf/table
                method: render_many
                data:
                  rs: rs:history
    -
      type: div
      attribute:
        class: col-md-6
      innerHTML:
        -
          type: div
          attribute:
            class: well
          innerHTML:
            -
              type: h2
              innerHTML: Links
            -
              type: widget
              settings:
                enabled: rs:has_links
              data:
                plugin: wf/table
                method: render_many
                data:
                  rs: rs:links
      